  language: objective-c
osx_image: xcode9.1
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator11.1
  - TVOS_SDK=appletvsimulator11.1
script:
  - xcodebuild -showsdks
  - xcodebuild -project UPDATE_CHECKER.xcodeproj -scheme 'UPDATE_CHECKER' -sdk $IOS_SDK build analyze

