language: objective-c  #1
osx_image: xcode9.2 #2

script: xcodebuild clean && xcodebuild build -sdk iphonesimulator9.0 -project UPDATE_CHECKER.xcodeproj -scheme UPDATE_CHECKER CODE_SIGNING_REQUIRED=NO
