language: objective-c  #1
osx_image: xcode9.2 #3

lane :build do |options|
  xcodebuild(
    project: "UPDATE_CHECKER.xcodeproj",
    scheme: "UPDATE_CHECKER",
    configuration: "Debug",
    clean: options[:clean],
    build: true,
    destination: "generic/platform=iOS",
    build_settings: {
      "CODE_SIGNING_REQUIRED" => "NO",
      "CODE_SIGN_IDENTITY" => ""
    }
  )
end
